### ISSUE TITLE
error curobo_gen_traj

### ISSUE THREAD

**Issue by seongjin-lim** [Lab-CORO/curobo_ros#14]
ros2 run curobo_ros curobo_gen_traj

An error occurs when you run that command.

May I know why?

root@ros1-docker:/home/ros2_ws# ros2 run curobo_ros curobo_gen_traj
Traceback (most recent call last):
  File "/home/ros2_ws/install/curobo_ros/lib/curobo_ros/curobo_gen_traj", line 33, in <module>
    sys.exit(load_entry_point('curobo-ros==0.0.0', 'console_scripts', 'curobo_gen_traj')())
  File "/home/ros2_ws/install/curobo_ros/lib/curobo_ros/curobo_gen_traj", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ros2_ws/install/curobo_ros/lib/python3.10/site-packages/curobo_ros/core/generate_trajectory.py", line 27, in <module>
    from capacinet_msg.srv import Fk
ModuleNotFoundError: No module named 'capacinet_msg'
[ros2run]: Process exited with failure 1
root@ros1-docker:/home/ros2_ws# ls /home/ros2_ws/install/capacitinet_msg/lib/python3.10/site-packages/

**Comment by saxtot** [comment]
Fixed in #13
